version: '3.8'


services:

  mongo:

    image: mongo

    container_name: mongo

    ports:

      - "27017:27017"

    volumes:

      - mongo-data:/data/db

    networks:

      - zapnet


  todo-app:

    image: priyansh26/3-tier-todo-app:v.1

    container_name: todo-app

    ports:

      - "3000:3000"

    environment:

      - MONGO_URI=mongodb://mongo:27017/todos

    depends_on:

      - mongo

    networks:

      - zapnet


volumes:

  mongo-data:


networks:

  zapnet:

    driver: bridge

